### ISSUE TITLE
Multiple instances when starting / restarting the adapter

### ISSUE THREAD

**Issue by oberstel** [oberstel/iobroker.pjlink#16]
I recognized that multiple instances of the adapter are trying to communicate with the projector which doesn‘t work.
A proper error message appears in the log (watch out for the Process ID)

Example:
`host.ioBroker-dev | 2019-11-25 21:12:59.096 | error | Caught by controller[1]: at WriteWrap.afterWrite [as oncomplete] (net.js:789:14) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }
-- | -- | -- | --
host.ioBroker-dev | 2019-11-25 21:12:59.096 | error | Caught by controller[1]: { Error: write EPIPE
host.ioBroker-dev | 2019-11-25 21:12:59.095 | error | Caught by controller[0]: at WriteWrap.afterWrite [as oncomplete] (net.js:789:14) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }
host.ioBroker-dev | 2019-11-25 21:12:59.094 | error | Caught by controller[0]: { Error: write EPIPE`

**Comment by oberstel** [comment]
yes, indeed - this is a known problem because the current version of the adapter isn't aware about asynchrones mode of operation when using JavaScript. The new version PJLinkV2 won't have this bug.
